//====================================================================================================
// Base code generated with LeatherGoods - ASF.Services.Contracts
// Architecture Solutions Foundation
//
// Generated by academic at LeatherGoods V 1.0 
//====================================================================================================

using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using ASF.Entities;


namespace ASF.Services.Contracts
{
    
    [DataContract]
    public class AllResponse
    {
        [DataMember]
        public List<Category> Result { get; set; }

        [DataMember]
        public List<Client> ResultClient { get; set; }

        [DataMember]
        public List<Cart> ResultCart { get; set; }

        [DataMember]
        public List<CartItem> ResultCartItem { get; set; }

        [DataMember]
        public List<Country> ResultCountry{ get; set; }

        [DataMember]
        public List<Dealer> ResultDealer { get; set; }

        [DataMember]
        public List<OrderDetail> ResultOrderDetail { get; set; }

        [DataMember]
        public List<OrderNumber> ResultOrderNumber { get; set; }

        [DataMember]
        public List<Order> ResultOrder { get; set; }

        [DataMember]
        public List<Product> ResultProduct { get; set; }

        [DataMember]
        public List<Rating> ResultRating { get; set; }

        [DataMember]
        public List<Setting> ResultSetting { get; set; }
    }
}

