//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASF.UI.WbSite.Resource {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyTexts() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASF.UI.WbSite.Resource.MyTexts", typeof(MyTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carrito.
        /// </summary>
        public static string Carrito {
            get {
                return ResourceManager.GetString("Carrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprar.
        /// </summary>
        public static string Comprar {
            get {
                return ResourceManager.GetString("Comprar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contactenos.
        /// </summary>
        public static string Contactenos {
            get {
                return ResourceManager.GetString("Contactenos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar.
        /// </summary>
        public static string Ingresar {
            get {
                return ResourceManager.GetString("Ingresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nosostros.
        /// </summary>
        public static string Nosotros {
            get {
                return ResourceManager.GetString("Nosotros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ordenes.
        /// </summary>
        public static string Ordenes {
            get {
                return ResourceManager.GetString("Ordenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar.
        /// </summary>
        public static string Registrar {
            get {
                return ResourceManager.GetString("Registrar", resourceCulture);
            }
        }
    }
}
